### PR TITLE
Writing/Mirroring clear traffic to pcap-file/network-Interface

### PR DESCRIPTION
**Pull request by cihankom**
To dump as pcap format , just use -X [filename] parameter.
To mirror clear traffic to network interface, just use -M [interface]  parameter.
To mirror clear traffic to destination host, specify ip address of destination with -T [ip addr]. But destination host should be in same subnet

### CODE REVIEW

**Comment by whitetiger21022014** [comment]
Dear Cihankom,
Great feature for sslsplit, I just tested with -X option, access to gmail, it can record incoming traffic (extract download attachment) , but when composing and sending attachment file it can not record
Could you check about record packets for both sides and also rotate that PCAP file when its size reached a limit?
Thanks

**Comment by cihankom** [comment]
Hi whitetiger
I will check it later. Thanks for your feedback.

Sincerely

**Comment by whitetiger21022014** [comment]
I used -M eth2 and got error as below:

tcp 192.168.111.200 62710 151.101.100.73 80
TCP connected to [151.101.100.73]:80
TCP connected from [192.168.111.200]:62710
Can't write packet: libnet_write_link(): only -1 bytes written (Message too long)

Warning: Failed to write to content log: Message too long
Main event loop stopped.
Received privsep req type 00 sz 1 on srvsock 10
Child proc 3247 exited with status 0

OS: Ubuntu 16.04.1 LTS

( note: mistake in  -X Interface Network Interface for mirroring, double -X option)

**Comment by cihankom** [comment]
Hi Whitetiger

Thanks for your feedback. I also relized this problem. I will fix it soon.
Thanks

**Comment by cihankom** [comment]
Hi Whitetiger
problem is fixed about "libnet_write_link error Message too long".
patch is committed. You can try.
Thanks again.

**Comment by whitetiger21022014** [comment]
Hi cihankom,
Thanks for your efforts, some notes as below
client <->  sslsplit( Ubuntu 2 NICs + 1 NIC for dummy)  <->  gmail.com
1)  -X myfile.pcap
   **Client sending:        Can NOT capture file**
   Client  receiving:      Capture file successfully
  
1)  -M to ens3 dummy interface, use tcpdump -s 0 -i ens3 myfile.pcap
   Client sending:        Capture file successfully
   **Client  receiving:      Can NOT capture file**

When can NOT capture, **PCAP size is so small**,
Best regards

**Comment by cihankom** [comment]
Hi Whitetiger 

how can you test it ? because I couldnt understand what the problem is clearly.
I test it from my site and request and response is captured succesfully.
Thanks

**Comment by whitetiger21022014** [comment]
Hi cihankom,
I test with transparent
iptables -t nat -A PREROUTING -p tcp --dport 443 -j REDIRECT --to-ports 8443
iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8080
mkdir /tmp/sslsplit
mkdir /tmp/sslsplit/logdir

sslsplit -D -l connections.log -j /tmp/sslsplit/ -k ca.key -c ca.crt ssl 0.0.0.0 8443 tcp 0.0.0.0 8080 -X myfile.pcap –u root

or sslsplit -D -l connections.log -j /tmp/sslsplit/ -k ca.key -c ca.crt ssl 0.0.0.0 8443 tcp 0.0.0.0 8080 -M ens3 –u root , and capture via tcpdump to pcap

**Example: Webmail client (Firefox, Gmail) sends/receives with attachment file size 8Mbytes
when extracting PCAP, i can not see attachment, PCAP size is so small, only ~2Mbytes,**

use -X:         Client sending: extract PCAP and can not see attachment file
or use -M:    Client receiving: extract PCAP and can not see attachment file
so strange

**Comment by cihankom** [comment]
Ok. I will try it . thanks

**Comment by whitetiger21022014** [comment]
I just recheck with -M. It seems Okay. Maybe i have mistake
I will test with -X
Btw you have mistake when typing in main_usage double -X characters
Thank you very much !

**Comment by cihankom** [comment]
Ok. I have just finished test also my site. Anyway we made double check.
I will fix usage. thanks for feedback
Sincerely.

**Comment by whitetiger21022014** [comment]
Hi Cihankom,
Option -T IppAdd_collect will check arp before running
This situation: if sslplit runs as service (initd), when rebooting sslsplit and at that time IppAdd_collect also down, so i think do not need to check arp when running with -T

**Comment by cihankom** [comment]
mirroring to destination host needs target mac  address. And so switch can deliver packet to destination. That why sslsplit send arp request and read arp response. Get mac addres from response and replace ethernet destination mac field of  TCP/IP packet with it.

Network interface should up when sslsplit running. 
If I can set some retrying for arp request, this solution will solve your problem?

**Comment by whitetiger21022014** [comment]
I use with -M option, it works so well for me

with -T, I think when destination host is down, sslsplit does not send anymore, and when destination is up it will resend
B/c destination host has to solve to MAC, so i guest you can use **-T MAC_address** it will fast, and always send all the time

**Comment by cihankom** [comment]
I think the best solution is to resend Arp Request forever and not mirroring any packet until response is read. Because when destination is down and switch can not deliver packet to destination. Because MAC Addr could not be found in switch memory. and so, switch will broadcast all packets to all ports . It will downgrade network performans.

**Comment by whitetiger21022014** [comment]
Ok, I will wait your commit that sslsplit can run forever

**Comment by cihankom** [comment]
Hi Whitetiget

You can try it now. I have just committed it. thanks

**Comment by whitetiger21022014** [comment]
I use with -M option, it works so well for me

with -T, I think when destination host is down, sslsplit does not send
anymore, and when destination is up it will resend
B/c destination host has to solve to MAC, so i guest you can use *-T
MAC_address* it will fast, and always send all the time

**Comment by whitetiger21022014** [comment]
Hi Cihankom,
IDS/IPS likes Suricata, BRO IDS or Snort,..
Do you know how to:  After Sslsplit decrypted traffic then use IDS/IPS analysis and **drop** connection if IDS/IPS detects keywork in **payload**?
Thank you

**Comment by cihankom** [comment]
Hi Whitetiger
IDS/IPS can analyze payload but it cant drop connection because sslsplit is making tcp headers with some emulated values. Sequence and Ack number is emulated in sslsplit. It is not real seq/ack number which is used encrypted ssl connection. Thats why ids/ips cant drop it, it needs real seq/ack number to drop it.

**Comment by whitetiger21022014** [comment]
Thank you
B/c I want to detect and block clients use Ultrasurf, SSL open proxy

**Comment by whitetiger21022014** [comment]
@cihankom ,
it is better if your commits available in https://github.com/droe/sslsplit/commits/develop

**Comment by droe** [comment]
- [ ] Quality check of proposed implementation (including network stack emulation, code style)
- [ ] Test build and functionality on different platforms (macOS homebrew, macOS macports, OpenBSD, FreeBSD, Linux distributions)
- [ ] Merge

**Comment by droe** [comment]
This code and feature set is included in #230, with significant improvements and bug fixes. Closing this issue. @cihankom, thank you for your contribution!

**Pull request closed without merging**
