### PR TITLE
Initial simple STARTTLS implementation

### PR DESCRIPTION
**Pull request by RichardPoole42**
"genericstarttls" feature as suggested in https://github.com/droe/sslsplit/issues/40 . Working and documented but certainly needs review before merge.

### CODE REVIEW

**Comment by RichardPoole42** [comment]
Three major things to be resolved before merge:

- I've cut-and-pasted quite a bit of code in ssl.c to do clienthello identification separately from looking for the SNI extension - perhaps this should be refactored now that there are essentially two different reasons to want to peek into a client hello message.

- I've used the name "genericstarttls" in the proxyspec but I'm not happy with it - the protocol I'm interested in (xmpp) calls this feature "starttls" but it is misleading to give the impression that the code looks at the higher-level protocol, as it just looks for the beginning of the SSL connection. Similarly, my new function and new variables and structure fields may be badly named.

- I've not added any unit tests - I think that at a minimum I should add one for the new proxyspec type.

**Comment by droe** [comment]
How about naming the proxy spec type `autossl`?

From a quick glance at the code I noticed that `ssl_tls_clienthello_identify` is within the `!OPENSSL_NO_TLSEXT` ifdef - that makes sense for `ssl_tls_clienthello_parse_sni` since SNI support depends on TLS extensions being available in OpenSSL, but not for detecting a Client Hello message where we a priori don't care if the version of OpenSSL supports TLS extensions or not.

**Comment by droe** [comment]
I'm currently working on this in a private branch. There are some stability issues with your proposed implementation that need to be ironed out before that code can be safely used. Will push the code to a public branch soon.

**Comment by droe** [comment]
I pushed this to a new branch `feature/autossl` - it is not quite ready for primetime but I am working on it.

**Pull request merged**
