### PR TITLE
Add OpenSSL engine support

### PR DESCRIPTION
**Pull request by droe**
Add the `-x` option to load and/or activate an OpenSSL engine. See issue #204 for a use case (AWS CloudHSM) and discussion.

### CODE REVIEW

**Comment by sonertari** [comment]
There were warnings on Linux with gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3):
```
ssl.c: In function ‘ssl_init’:
ssl.c:370:2: warning: ‘OPENSSL_config’ is deprecated [-Wdeprecated-declarations]
  OPENSSL_config(NULL);
  ^~~~~~~~~~~~~~
In file included from /usr/include/openssl/ct.h:13:0,
                 from /usr/include/openssl/ssl.h:61,
                 from ssl.h:35,
                 from ssl.c:29:
/usr/include/openssl/conf.h:92:1: note: declared here
 DEPRECATEDIN_1_1_0(void OPENSSL_config(const char *config_name))
 ^
```

I read that OPENSSL_config() is not needed for OPENSSL_VERSION_NUMBER >= 0x10100000L.

```
ssl.t.c: In function ‘ssl_engine_01’:
ssl.t.c:765:2: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
  (void)asprintf(&path, "%s/extra/engine/dummy-engine."DLSUFFIX, cwd);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

Prepending an UNUSED with a dummy var fixes this warning.


Make test errored out on OpenBSD 6.3 with clang version 5.0.1 (tags/RELEASE_501/final) (based on LLVM 5.0.1)
Target: amd64-unknown-openbsd6.3

```
ssl.t.c:754:11: error: use of undeclared identifier 'PATH_MAX'
        char cwd[PATH_MAX];
                 ^
```

Adding `#include <limits.h>` at the top of that file fixes this error.

Also, tests fail on both platforms with the following message:
``` 
ssl.t.c:767:F:ssl_engine:ssl_engine_01:0: loading OpenSSL engine failed
```

I guess this was expected.

I have fixed the errors and warning on the `engine_review` branch. Please review it.

**Comment by droe** [comment]
Thanks! Merged your changes into `engine`.

**Comment by droe** [comment]
The failure of the `ssl_engine_01` test is *not* expected. That actually needs a solution. Your test systems are both OpenSSL 1.1.x, right?

**Comment by droe** [comment]
@sonertari Can you test drive the new OpenSSL 1.1.x initialization code? It now works for me with OpenSSL 1.1.0i on macOS, but only if the dummy engine in `extra/engine` is compiled with the same version of OpenSSL.

**Comment by sonertari** [comment]
Linux tests are fixed, no failures.

OpenBSD tests still give:
```
ssl.t.c:768:F:ssl_engine:ssl_engine_01:0: loading OpenSSL engine failed
```
Btw, on Linux: `OpenSSL 1.1.0g  2 Nov 2017` and on OpenBSD `LibreSSL 2.7.4`

I'm also looking at the OpenBSD test failure. Based on my tests and investigation in the last couple of days I think LibreSSL 2.7.4 behaves like OPENSSL_VERSION_NUMBER < 0x1000200fL (I'm still testing).

**Comment by droe** [comment]
The test would also fail if LibreSSL defines OPENSSL_NO_ENGINE, i.e. is built without engine support. You can check ./sslsplit -V for engine support. I'll make the test conditional on OPENSSL_NO_ENGINE.

**Comment by sonertari** [comment]
It claims it has engine support:
```
$ ./sslsplit -V
SSLsplit 0.5.3-67-g7e2680b (built 2018-08-23)
Copyright (c) 2009-2018, Daniel Roethlisberger <daniel@roe.ch>
https://www.roe.ch/SSLsplit
Build info: V:GIT
Features: -DHAVE_IPFW -DHAVE_PF
NAT engines: pf* ipfw
Local process info support: no
compiled against LibreSSL 2.7.4 (20000000)
rtlinked against LibreSSL 2.7.4 (20000000)
LibreSSL detected: LibreSSL 2.7.4 (2070400f)
OpenSSL has support for TLS extensions
TLS Server Name Indication (SNI) supported
OpenSSL is thread-safe with THREADID
OpenSSL has engine support
Using SSL_MODE_RELEASE_BUFFERS
SSL/TLS protocol availability: tls10 tls11 tls12 
SSL/TLS algorithm availability: !SHA0 RSA DSA ECDSA DH ECDH EC
OpenSSL option availability: SSL_OP_NO_COMPRESSION SSL_OP_NO_TICKET SSL_OP_ALLOW_UNSAFE_LEGACY_RENEGOTIATION SSL_OP_DONT_INSERT_EMPTY_FRAGMENTS SSL_OP_NO_SESSION_RESUMPTION_ON_RENEGOTIATION SSL_OP_TLS_ROLLBACK_BUG
compiled against libevent 2.1.8-stable
rtlinked against libevent 2.1.8-stable
2 CPU cores detected
```

**Comment by droe** [comment]
I can reproduce the failure using LibreSSL 2.7.4 on macOS too.

**Comment by droe** [comment]
LibreSSL 2.7.4 does seem to support engines on a source code level, but the openssl utility it provides does not seem to support any engine-related commands or options (`openssl engine`, `-engine`). Quite difficult to debug engine support without that. I'll disable engine support when building against LibreSSL for now.

**Comment by sonertari** [comment]
Yes, the same here on OpenBSD too, contrary to LibreSSL [README.ENGINE](https://github.com/libressl/libressl/blob/master/src/README.ENGINE).

So, with your last commit, all seems fine to me now, on Linux and OpenBSD.

**Comment by droe** [comment]
Squash-merged to `develop`. Thanks Soner!

**Pull request closed without merging**
