### PR TITLE
Add fixes for OpenSSL 1.1 while retaining 1.0 compatibility

### PR DESCRIPTION
**Pull request by hillu**
This is the patch I added to the Debian package of 0.5.0 which I just uploaded to Debian/unstable. This should fix what was reported in issue #148.

### CODE REVIEW

**Comment by pduldig-at-tw** [comment]
I also attempted to port to openssl 1.1; but yours is more careful and cleaner.

**Comment by hillu** [comment]
@pduldig-at-tw Can you verify that with this patch everything still works for you?

**Comment by scorpius** [comment]
I got the following when using *imap*. 
**Peeking did not yield a (truncated) ClientHello message, aborting connection**

**Comment by droe** [comment]
A slightly adapted version of this was merged, thanks for your contribution.

**Pull request closed without merging**
