### PR TITLE
add support for dst/src addr/port pathspecs

### PR DESCRIPTION
**Pull request by AdamJacobMuller**
add support for:
```
%f - dest address
%h - dest port
%t - source address
%v - source port
```
format specifiers to pathspec

The goal of this is to allow pathspecs like:
```
/var/log/sslsplit/%t/%f/%h/%T
```

This improves upon the existing %s/%d for two big reasons

#1 using %s/%d results in unusable directory structures, because of the inclusion of the randomized source port address

#2 the inclusion of the brackets inside the %s/%d specifiers is sub-optimal in filesystems

I would point out, I am *not* a C programmer by trade and barely know C, this patch does work for me but is perhaps sub-optimal. Comments/improvements are definitely welcome.

### CODE REVIEW

**Comment by droe** [comment]
Your solution causes getnameinfo() to be called twice for every endpoint (once for the host and once for the port). Can you change that into a single call of getnameinfo() by writing a derivative of sys_sockaddr_str() that returns host and port into separate buffers but only calls getnameinfo() once, instead of having separate helpers for host and port?

**Comment by AdamJacobMuller** [comment]
I can *try* but no promises :) I'm really not a c programmer.

Aside from that, does the patch look ok?

**Comment by droe** [comment]
Thanks! I try to thoroughly test patches before merging them so no worries :)
On first glance the patch looks ok, yes, but I did not test it yet.

**Comment by droe** [comment]
Are you still working on this?

**Comment by droe** [comment]
FYI, I'm now working on separating host and port into distinct members of the state ctx structure and rewriting `sys_sockaddr_str()` to facilitate that.

**Comment by droe** [comment]
Merged to `develop` with some modifications. Thanks for your contribution!

**Pull request closed without merging**
